


exports.config = {
    MAX_NODES          : 100,
    SIMULATION_TIMEOUT : 5000,
    PULSE_PERIODICITY  : 1000,
    MAX_KEYS_COUNT     : 10,
    MAX_TRANSACTIONS   : 1000,
    MAX_TRANSACTION_TIME: 2000
};



