


exports.config = {
    MAX_NODES          : 10,
    SIMULATION_TIMEOUT : 30000,
    PULSE_PERIODICITY  : 2000,
    MAX_KEYS_COUNT     : 100,
    MAX_TRANSACTIONS   : 10000,
    MAX_TRANSACTION_TIME: 5000,
    NETWORK_DELAY      : 7000
};


GLOBAL_MAX_TRANSACTION_TIME = exports.config.MAX_TRANSACTION_TIME / 1000;
